apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-a-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-a
  template:
    metadata:
      labels:
        app: project-a
    spec:
      containers:
      - name: app
        image: project-a-big:latest
        ports:
        - containerPort: 3000
